Issue 2 temp calculator
Xarvius/TIL pull request #10
Opened 2019-09-06 11:05 UTC by Xarvius

2019-09-06 15:17 UTC, noisy requested changes

2019-09-06 15:17 UTC, noisy commented on programs/issue-2-temp-calculator/run.py
> +            user_request = int(input("Wybierz: "))
nic ważnego, ale unikałbym używania słowa `request`. Zazwyczaj ludziom się ono kojarzy z http requestem, który się otrzymuje, jak ktos zrobi zapytanie do serwera. Może `option`?

ps. https://twitter.com/codinghorror/status/506010907021828096

2019-09-06 15:17 UTC, noisy commented on programs/issue-2-temp-calculator/run.py
> +        if not 2 >= user_request >= 1:
dziwnie od tyłu się to czyta. Bardziej naturalnie było by:

`1 <= user_request <= 2:`

2019-09-06 15:17 UTC, noisy commented on programs/issue-2-temp-calculator/run.py
> +        if not 2 >= user_request >= 1:
Swoją drogą, python wyznaje zasadę:

> Easier to ask for forgiveness than permission. This common Python coding style assumes the existence of valid keys or attributes and catches exceptions if the assumption proves false. This clean and fast style is characterized by the presence of many try and except statements. The technique contrasts with the LBYL style common to many other languages such as C.

źródło: https://docs.python.org/3.4/glossary.html

Pomyśl, co byś musiał zrobić, byś mógł założyć, że użytkownik podad poprawną opcję, a jeżeli podałby złą, to poleciałby wyjątek rzucony przez pythona, a ty byś tylko go złapał i tam wyświetlił, nie istnieje taka opcja...

2019-09-06 15:17 UTC, noisy commented on programs/issue-2-temp-calculator/run.py
> +menu()
dobrym zwyczajem jest zostawiać na końu zawsze pustą linię. 

![Selection_999(212)](https://user-images.githubusercontent.com/201263/64439277-e3c73d00-d0c9-11e9-9318-5a5cf3dee041.png)

Ustaw sobie swój edytor, by sam tego pilnował i dodawał ewentualnie brakującą linie, gdyby jej brakowało.

A dlaczego warto  jest dodawać nową linię? Bo jeżeli kiedyś coś nowego dodasz do następnej lini, to wtedy w diffie będzie widoczna zmiana tej nowej lini. A tak to byś widział zmiany w dwóch liniach. Dopisanie znaku nowej lini do lini 39, tuż za `menu()` i nowa linia.

I tym samym git blame pokazałby wówczas, że to ty zmieniłeś obie linie.

2019-09-06 15:52 UTC, noisy commented on programs/issue-2-temp-calculator/run.py
> +        if not 2 >= user_request >= 1:
> Pomyśl, co byś musiał zrobić
sam o tym wspomniałeś, więc dobrecyzuje tutaj... żebyś nad tym nie siedział teraz, bo to nie pora. Mógłbyś zrobic tak, by wszystkie dane do konwersji trzymać w jakimś słowniku czy liście... i jeżeli ktoś wybrał by coś z poza listy, to wtedy leciałby wyjątek...

Ale tego tutaj nie implementuj. Miałeś się tylko zastanowić :)

2019-09-06 23:15 UTC, Xarvius commented
done

2019-09-07 07:59 UTC, noisy commented on programs/issue-2-temp-calculator/run.py
> +            user_options = int(input("Wybierz: "))
czepiając się, powinno być w sumie chyba raczej "user option", w liczbie pojedynczej. W końcu użytkownik wybiera jedną opcje ;) Ale mało ważne. Możesz poprawić to przy okazji innego Pull Requesta

2019-09-07 08:00 UTC, noisy approved these changes

2019-09-07 08:05 UTC, noisy commented
@Xarvius before merge, please rebase your commits onto master. Currently your history looks very non-linear, and is very ugly:

![Selection_999(215)](https://user-images.githubusercontent.com/201263/64471880-efad1080-d156-11e9-8f34-8410cacb171a.png)

2019-09-07 08:09 UTC, noisy requested changes
please rebase to latest master

2019-09-07 10:42 UTC, noisy approved these changes

2019-09-07 10:43 UTC, merged